"""empty message

<<<<<<<< HEAD:migrations/versions/9fc0253ebd19_.py
Revision ID: 9fc0253ebd19
Revises: 
Create Date: 2023-08-27 07:26:49.047411
========
Revision ID: d46812469708
Revises: 
Create Date: 2023-08-26 20:02:17.484733
>>>>>>>> 33e5fc183d39a37191b939e318d268d8d1a82070:migrations/versions/d46812469708_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/9fc0253ebd19_.py
revision = '9fc0253ebd19'
========
revision = 'd46812469708'
>>>>>>>> 33e5fc183d39a37191b939e318d268d8d1a82070:migrations/versions/d46812469708_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('money_register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tipo_movimiento', sa.String(length=500), nullable=False),
    sa.Column('tipo_categoria', sa.String(length=500), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('money_register')
    op.drop_table('user')
    # ### end Alembic commands ###
