"""empty message

Revision ID: d5eb87bac12c
Revises: f927d2e8d0c0
Create Date: 2023-08-25 13:35:27.511090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5eb87bac12c'
down_revision = 'f927d2e8d0c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('money_register', schema=None) as batch_op:
        batch_op.drop_column('tipo_moneda')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('money_register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_moneda', sa.VARCHAR(length=200), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
